### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by gDKdev** [iRath96/webNBT#1]
How can I use your webNBT libary in my own projects?
Could you add a documentation? Or anything that I know which functions need to be called?

**Comment by iRath96** [comment]
Include the file [`/web-app/NBT.js`](https://github.com/iRath96/webNBT/blob/master/web-app/NBT.js) (you're also required to have [`/web-app/NBT.js.mem`](https://github.com/iRath96/webNBT/blob/master/web-app/NBT.js.mem) in the same folder). `NBT.js` was compiled from the C++-files in [`/nbt-utils/`](https://github.com/iRath96/webNBT/tree/master/nbt-utils) (and zlib as dependency) using emscripten, so if you want to alter the behavior of `NBT.js`, you'll have to edit the C++-files and recompile.

The most important methods exposed by `NBT.js` are:
`Module.Tag.serialize` and `Module.Tag.serializeCompressed` (these transform `Tag`s into binary data)
`Module.Tag.deserialize` and `Module.Tag.deserializeCompressed` (these load `Tag`s from binary data)

For more information on the methods exposed by `NBT.js` (especially instance methods of `Tag`s) take a look at the emscripten bindings in [`/nbt-utils/main.cpp`](https://github.com/iRath96/webNBT/blob/master/nbt-utils/main.cpp).

If there's anything else you need, let me know and I'll help you.

**Comment by gDKdev** [comment]
Thanks man. Do I also need to wait for the depencies like in the app.js?

**Comment by iRath96** [comment]
No problem. You'll probably have to wait for the dependencies as well, I haven't found a better way to accomplish this.

The parameters for `deserialize` should be `static Tag *deserialize(std::string input, bool withName = true, TagType::Enum type = TagType::Unknown) {` (see [here](https://github.com/iRath96/webNBT/blob/master/nbt-utils/nbt_utils.h#L74))

So basically

1. String: data
2. Boolean: named?
3. Tag Type: set this to -1 and it'll read the type from the data provided.

You can take a look at how I call `deserialize` within the [`App.js`](https://github.com/iRath96/webNBT/blob/master/web-app/src/App.js#L102).

Hope this helps. 🐱

**Comment by gDKdev** [comment]
Got it :) Thanks. And I've seen that I can iterate throu the Tag with [this](https://github.com/iRath96/webNBT/blob/master/web-app/src/TagLibrary.js#L45).
