### ISSUE TITLE
Having Issues With level.dat

### ISSUE THREAD

**Issue by janagyjr** [iRath96/webNBT#6]
The included file (made by Enigmatica 2: Expert 1.69) generates an error (attached).

Level dot dat: [level.zip](https://github.com/iRath96/webNBT/files/3744858/level.zip)

Error: [webnbt](https://user-images.githubusercontent.com/23646259/67111365-4f6df100-f1c4-11e9-96c5-daa3c8d78f6c.png)

**Comment by NA0341** [comment]
**Confirmed** ✔️

Got the same error with another file from a world (maybe modded & maybe mc v1.6.4 o. 1.7.10) mostly empty data stream - see attachment: [level.zip](https://github.com/iRath96/webNBT/files/4025941/level.zip)

After clicking **cancel**, it displays contents (as normal?)
