### ISSUE TITLE
Just Wanted To Point Out, This Can No Longer Read NBT Data From 1.16.1

### ISSUE THREAD

**Issue by alexis-evelyn** [iRath96/webNBT#9]
This can no longer read data from 1.16.1.

**Comment by iRath96** [comment]
Thanks for opening this issue. I am having trouble reproducing this, however. Can you be a bit more precise? Which file were you trying to open?

**Comment by iRath96** [comment]
@alexis-evelyn This might have been due to the previous lack of `TAG_Long_Array` support, which I have now included. Can you try again and see if it works now? Otherwise, please send me the file that is causing issues.

**Comment by alexis-evelyn** [comment]
Yes, it works now! Thanks!
